### ISSUE TITLE
Explore

### ISSUE THREAD

**Issue by Shriyanshagro** [collective/collective.ifttt#14]
- [x] Sphinx for Documentation
- [x] IFTTT workflow

**Comment by datakurre** [comment]
@Shriyanshagro Not in documentation, but all strings in the add-on should use translatable strings so that contributors can later translate this to their own language.

See how ``_`` is imported and used e.g. in

https://training.plone.org/5/mastering-plone/dexterity_3.html#the-python-schema

For you, it's defined here https://github.com/collective/collective.ifttt/blob/master/src/collective/ifttt/__init__.py

This script is used to update translatable strings and localizations

https://github.com/collective/collective.ifttt/blob/master/src/collective/ifttt/locales/update.sh

So, as long as you use ``_`` properly to use translatable strings instead of hard coded English values, the package can be localized. You don't need to localize it, just keep it localizable ("internationalized").

**Comment by Shriyanshagro** [comment]
@datakurre , so I kept every config to be default while installing sphinx. Is that okay?

**Comment by datakurre** [comment]
@Shriyanshagro Yes it should be ok.

**Comment by Shriyanshagro** [comment]
This issue has no fix and was all about TODO which are accomplished.
