### ISSUE TITLE
Story 16 : Release to Pypi : 2 Points

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#61]
As a Plone integrator, I will be able to add collective.ifttt easily to my buildout because it is released on Pypi.

@datakurre please add technical details and verify number of points I chose. (It's easy but will require some learning and figuring out credentials etc.) Thanks!

**Comment by datakurre** [comment]
the project already comes with zest.releaser (the most sane tool for publishing Python packages) configured in the buildout so that there should be command

bin/fullrelease

available.

Publishing is basically

1. Create account into http://pypi.io
2. Update CHANGES.rst
3. Run bin/fullrelease and follow its instructions

http://zestreleaser.readthedocs.io/en/latest/uploading.html

Later it would be good to share maintenance of the package at http://pypi.io with some community members. I assume that ”collective” username is owned by someone known in our community.

**Comment by datakurre** [comment]
2 points sound correct

**Comment by datakurre** [comment]
@Shriyanshagro Example `~/.pypirc`

```
[distutils]                                                                                                                            
index-servers =
    pypi

[pypi]
username: YOUR_USERNAME
password: YOUR_PASSWORD
```

**Comment by datakurre** [comment]
@Shriyanshagro The current CHANGELOG with initial release as 1.0a is ok

About versioning. If this project would go on, it would follow semantic versioning https://semver.org/ with the exception that major releases are 1.0 and 2.0, not 1.0.0 or 2.0.0

```
Changelog
=========


1.0a1 (unreleased)
------------------

- Initial release.
  [Shriyanshagro]
```

**Comment by datakurre** [comment]
https://pypi.org/project/collective.ifttt/
